<?php

/**
 * @file
 */

/**
 * Implements hook_install().
 */
function commerce_bpost_pickup_test_install() {
  // Enable Bpost pickup point on the shipping method.
  $methods = \Drupal::entityTypeManager()->getStorage('commerce_shipping_method')->loadByProperties(['name' => 'BPost']);
  $method = reset($methods);
  $config = $method->get('plugin')->target_plugin_configuration;
  $config['services'][] = 'pickup_point';
  $config['service_configuration']['pickup_point']['rate_amounts']['national'] = [
    '0_2000' => ['number' => '14', 'currency_code' => 'EUR'],
    '2001_5000' => ['number' => '19', 'currency_code' => 'EUR'],
  ];
  $config['service_configuration']['pickup_point']['supports_international'] = '0';
  $method->set('plugin', [
    'target_plugin_id' => 'bpost',
    'target_plugin_configuration' => $config,
  ]);
  $method->save();
}
